artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/mohamedmagri/ProjetSkier/raw/master/Orange_data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/Orange_data.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_preparation:
  root_dir: artifacts/data_preparation
  data_path: artifacts/data_ingestion/Orange_data.csv




model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_preparation/train_LTE.csv
  test_data_path: artifacts/data_preparation/test_LTE.csv
  model_name: model.joblib



model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_preparation/test_LTE.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json



best_model_trainer:
  root_dir: artifacts/best_model_trainer
  train_data_path: artifacts/data_preparation/train_LTE.csv
  test_data_path: artifacts/data_preparation/test_LTE.csv


